// <auto-generated />
using System;
using DaveNatalie.CarMediaDevTest.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DaveNatalie.CarMediaDevTest.Migrations
{
    [DbContext(typeof(MusicDbContext))]
    partial class MusicDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.9");

            modelBuilder.Entity("DaveNatalie.CarMediaDevTest.Models.Album", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ArtistId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("YearReleased")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.ToTable("Albums");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ArtistId = 1L,
                            Created = new DateTimeOffset(new DateTime(2022, 9, 28, 16, 24, 43, 499, DateTimeKind.Unspecified).AddTicks(2883), new TimeSpan(0, -4, 0, 0, 0)),
                            Name = "Drones",
                            YearReleased = 2015
                        },
                        new
                        {
                            Id = 2L,
                            ArtistId = 1L,
                            Created = new DateTimeOffset(new DateTime(2022, 9, 28, 16, 24, 43, 499, DateTimeKind.Unspecified).AddTicks(2900), new TimeSpan(0, -4, 0, 0, 0)),
                            Name = "Origin of Symmetry",
                            YearReleased = 2001
                        },
                        new
                        {
                            Id = 3L,
                            ArtistId = 2L,
                            Created = new DateTimeOffset(new DateTime(2022, 9, 28, 16, 24, 43, 499, DateTimeKind.Unspecified).AddTicks(2912), new TimeSpan(0, -4, 0, 0, 0)),
                            Name = "Rio",
                            YearReleased = 1982
                        },
                        new
                        {
                            Id = 4L,
                            ArtistId = 3L,
                            Created = new DateTimeOffset(new DateTime(2022, 9, 28, 16, 24, 43, 499, DateTimeKind.Unspecified).AddTicks(2924), new TimeSpan(0, -4, 0, 0, 0)),
                            Name = "1984",
                            YearReleased = 1984
                        });
                });

            modelBuilder.Entity("DaveNatalie.CarMediaDevTest.Models.Artist", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Created = new DateTimeOffset(new DateTime(2022, 9, 28, 16, 24, 43, 499, DateTimeKind.Unspecified).AddTicks(2772), new TimeSpan(0, -4, 0, 0, 0)),
                            Name = "Muse"
                        },
                        new
                        {
                            Id = 2L,
                            Created = new DateTimeOffset(new DateTime(2022, 9, 28, 16, 24, 43, 499, DateTimeKind.Unspecified).AddTicks(2857), new TimeSpan(0, -4, 0, 0, 0)),
                            Name = "Duran Duran"
                        },
                        new
                        {
                            Id = 3L,
                            Created = new DateTimeOffset(new DateTime(2022, 9, 28, 16, 24, 43, 499, DateTimeKind.Unspecified).AddTicks(2869), new TimeSpan(0, -4, 0, 0, 0)),
                            Name = "Van Halen"
                        });
                });

            modelBuilder.Entity("DaveNatalie.CarMediaDevTest.Models.Song", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AlbumId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Track")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AlbumId = 1L,
                            Created = new DateTimeOffset(new DateTime(2022, 9, 28, 16, 24, 43, 499, DateTimeKind.Unspecified).AddTicks(2937), new TimeSpan(0, -4, 0, 0, 0)),
                            Name = "Dead Inside",
                            Track = 1
                        },
                        new
                        {
                            Id = 2L,
                            AlbumId = 1L,
                            Created = new DateTimeOffset(new DateTime(2022, 9, 28, 16, 24, 43, 499, DateTimeKind.Unspecified).AddTicks(2951), new TimeSpan(0, -4, 0, 0, 0)),
                            Name = "Drill Sargeant",
                            Track = 2
                        },
                        new
                        {
                            Id = 3L,
                            AlbumId = 1L,
                            Created = new DateTimeOffset(new DateTime(2022, 9, 28, 16, 24, 43, 499, DateTimeKind.Unspecified).AddTicks(2962), new TimeSpan(0, -4, 0, 0, 0)),
                            Name = "Psycho",
                            Track = 3
                        },
                        new
                        {
                            Id = 4L,
                            AlbumId = 1L,
                            Created = new DateTimeOffset(new DateTime(2022, 9, 28, 16, 24, 43, 499, DateTimeKind.Unspecified).AddTicks(2974), new TimeSpan(0, -4, 0, 0, 0)),
                            Name = "Mercy",
                            Track = 4
                        },
                        new
                        {
                            Id = 5L,
                            AlbumId = 1L,
                            Created = new DateTimeOffset(new DateTime(2022, 9, 28, 16, 24, 43, 499, DateTimeKind.Unspecified).AddTicks(2986), new TimeSpan(0, -4, 0, 0, 0)),
                            Name = "Reapers",
                            Track = 5
                        },
                        new
                        {
                            Id = 6L,
                            AlbumId = 1L,
                            Created = new DateTimeOffset(new DateTime(2022, 9, 28, 16, 24, 43, 499, DateTimeKind.Unspecified).AddTicks(3000), new TimeSpan(0, -4, 0, 0, 0)),
                            Name = "The Handler",
                            Track = 6
                        },
                        new
                        {
                            Id = 7L,
                            AlbumId = 1L,
                            Created = new DateTimeOffset(new DateTime(2022, 9, 28, 16, 24, 43, 499, DateTimeKind.Unspecified).AddTicks(3011), new TimeSpan(0, -4, 0, 0, 0)),
                            Name = "JFK",
                            Track = 7
                        },
                        new
                        {
                            Id = 8L,
                            AlbumId = 1L,
                            Created = new DateTimeOffset(new DateTime(2022, 9, 28, 16, 24, 43, 499, DateTimeKind.Unspecified).AddTicks(3023), new TimeSpan(0, -4, 0, 0, 0)),
                            Name = "Defector",
                            Track = 8
                        },
                        new
                        {
                            Id = 9L,
                            AlbumId = 1L,
                            Created = new DateTimeOffset(new DateTime(2022, 9, 28, 16, 24, 43, 499, DateTimeKind.Unspecified).AddTicks(3034), new TimeSpan(0, -4, 0, 0, 0)),
                            Name = "Revolt",
                            Track = 9
                        },
                        new
                        {
                            Id = 10L,
                            AlbumId = 1L,
                            Created = new DateTimeOffset(new DateTime(2022, 9, 28, 16, 24, 43, 499, DateTimeKind.Unspecified).AddTicks(3047), new TimeSpan(0, -4, 0, 0, 0)),
                            Name = "Aftermath",
                            Track = 10
                        },
                        new
                        {
                            Id = 11L,
                            AlbumId = 1L,
                            Created = new DateTimeOffset(new DateTime(2022, 9, 28, 16, 24, 43, 499, DateTimeKind.Unspecified).AddTicks(3059), new TimeSpan(0, -4, 0, 0, 0)),
                            Name = "The Globalist",
                            Track = 11
                        },
                        new
                        {
                            Id = 12L,
                            AlbumId = 1L,
                            Created = new DateTimeOffset(new DateTime(2022, 9, 28, 16, 24, 43, 499, DateTimeKind.Unspecified).AddTicks(3070), new TimeSpan(0, -4, 0, 0, 0)),
                            Name = "Drones",
                            Track = 12
                        },
                        new
                        {
                            Id = 13L,
                            AlbumId = 2L,
                            Created = new DateTimeOffset(new DateTime(2022, 9, 28, 16, 24, 43, 499, DateTimeKind.Unspecified).AddTicks(3156), new TimeSpan(0, -4, 0, 0, 0)),
                            Name = "Intro",
                            Track = 1
                        },
                        new
                        {
                            Id = 14L,
                            AlbumId = 2L,
                            Created = new DateTimeOffset(new DateTime(2022, 9, 28, 16, 24, 43, 499, DateTimeKind.Unspecified).AddTicks(3169), new TimeSpan(0, -4, 0, 0, 0)),
                            Name = "Apocolypse Please",
                            Track = 2
                        },
                        new
                        {
                            Id = 15L,
                            AlbumId = 2L,
                            Created = new DateTimeOffset(new DateTime(2022, 9, 28, 16, 24, 43, 499, DateTimeKind.Unspecified).AddTicks(3180), new TimeSpan(0, -4, 0, 0, 0)),
                            Name = "Time is Running Out",
                            Track = 3
                        },
                        new
                        {
                            Id = 16L,
                            AlbumId = 2L,
                            Created = new DateTimeOffset(new DateTime(2022, 9, 28, 16, 24, 43, 499, DateTimeKind.Unspecified).AddTicks(3192), new TimeSpan(0, -4, 0, 0, 0)),
                            Name = "Sing for Absolution",
                            Track = 4
                        },
                        new
                        {
                            Id = 17L,
                            AlbumId = 2L,
                            Created = new DateTimeOffset(new DateTime(2022, 9, 28, 16, 24, 43, 499, DateTimeKind.Unspecified).AddTicks(3203), new TimeSpan(0, -4, 0, 0, 0)),
                            Name = "Stokholm Syndrome",
                            Track = 5
                        },
                        new
                        {
                            Id = 18L,
                            AlbumId = 2L,
                            Created = new DateTimeOffset(new DateTime(2022, 9, 28, 16, 24, 43, 499, DateTimeKind.Unspecified).AddTicks(3216), new TimeSpan(0, -4, 0, 0, 0)),
                            Name = "Falling Away With you",
                            Track = 6
                        },
                        new
                        {
                            Id = 19L,
                            AlbumId = 2L,
                            Created = new DateTimeOffset(new DateTime(2022, 9, 28, 16, 24, 43, 499, DateTimeKind.Unspecified).AddTicks(3228), new TimeSpan(0, -4, 0, 0, 0)),
                            Name = "Interlude",
                            Track = 7
                        },
                        new
                        {
                            Id = 20L,
                            AlbumId = 2L,
                            Created = new DateTimeOffset(new DateTime(2022, 9, 28, 16, 24, 43, 499, DateTimeKind.Unspecified).AddTicks(3240), new TimeSpan(0, -4, 0, 0, 0)),
                            Name = "Hysteria",
                            Track = 8
                        },
                        new
                        {
                            Id = 21L,
                            AlbumId = 2L,
                            Created = new DateTimeOffset(new DateTime(2022, 9, 28, 16, 24, 43, 499, DateTimeKind.Unspecified).AddTicks(3251), new TimeSpan(0, -4, 0, 0, 0)),
                            Name = "Blackout",
                            Track = 9
                        },
                        new
                        {
                            Id = 22L,
                            AlbumId = 2L,
                            Created = new DateTimeOffset(new DateTime(2022, 9, 28, 16, 24, 43, 499, DateTimeKind.Unspecified).AddTicks(3263), new TimeSpan(0, -4, 0, 0, 0)),
                            Name = "Butterflies and Hurricanes",
                            Track = 10
                        },
                        new
                        {
                            Id = 23L,
                            AlbumId = 2L,
                            Created = new DateTimeOffset(new DateTime(2022, 9, 28, 16, 24, 43, 499, DateTimeKind.Unspecified).AddTicks(3274), new TimeSpan(0, -4, 0, 0, 0)),
                            Name = "The Small Print",
                            Track = 11
                        },
                        new
                        {
                            Id = 24L,
                            AlbumId = 2L,
                            Created = new DateTimeOffset(new DateTime(2022, 9, 28, 16, 24, 43, 499, DateTimeKind.Unspecified).AddTicks(3286), new TimeSpan(0, -4, 0, 0, 0)),
                            Name = "Endlessly",
                            Track = 12
                        },
                        new
                        {
                            Id = 25L,
                            AlbumId = 2L,
                            Created = new DateTimeOffset(new DateTime(2022, 9, 28, 16, 24, 43, 499, DateTimeKind.Unspecified).AddTicks(3298), new TimeSpan(0, -4, 0, 0, 0)),
                            Name = "Thoughts of a Dying Athiest",
                            Track = 13
                        },
                        new
                        {
                            Id = 26L,
                            AlbumId = 2L,
                            Created = new DateTimeOffset(new DateTime(2022, 9, 28, 16, 24, 43, 499, DateTimeKind.Unspecified).AddTicks(3309), new TimeSpan(0, -4, 0, 0, 0)),
                            Name = "Ruled by Secrecy",
                            Track = 14
                        },
                        new
                        {
                            Id = 27L,
                            AlbumId = 2L,
                            Created = new DateTimeOffset(new DateTime(2022, 9, 28, 16, 24, 43, 499, DateTimeKind.Unspecified).AddTicks(3321), new TimeSpan(0, -4, 0, 0, 0)),
                            Name = "Fury",
                            Track = 15
                        },
                        new
                        {
                            Id = 28L,
                            AlbumId = 3L,
                            Created = new DateTimeOffset(new DateTime(2022, 9, 28, 16, 24, 43, 499, DateTimeKind.Unspecified).AddTicks(3332), new TimeSpan(0, -4, 0, 0, 0)),
                            Name = "Rio",
                            Track = 1
                        },
                        new
                        {
                            Id = 29L,
                            AlbumId = 3L,
                            Created = new DateTimeOffset(new DateTime(2022, 9, 28, 16, 24, 43, 499, DateTimeKind.Unspecified).AddTicks(3344), new TimeSpan(0, -4, 0, 0, 0)),
                            Name = "My Own Way",
                            Track = 2
                        },
                        new
                        {
                            Id = 30L,
                            AlbumId = 3L,
                            Created = new DateTimeOffset(new DateTime(2022, 9, 28, 16, 24, 43, 499, DateTimeKind.Unspecified).AddTicks(3356), new TimeSpan(0, -4, 0, 0, 0)),
                            Name = "Lonely in Your Nightmare",
                            Track = 3
                        },
                        new
                        {
                            Id = 31L,
                            AlbumId = 3L,
                            Created = new DateTimeOffset(new DateTime(2022, 9, 28, 16, 24, 43, 499, DateTimeKind.Unspecified).AddTicks(3367), new TimeSpan(0, -4, 0, 0, 0)),
                            Name = "Hungry Like the Wolf",
                            Track = 4
                        },
                        new
                        {
                            Id = 32L,
                            AlbumId = 3L,
                            Created = new DateTimeOffset(new DateTime(2022, 9, 28, 16, 24, 43, 499, DateTimeKind.Unspecified).AddTicks(3379), new TimeSpan(0, -4, 0, 0, 0)),
                            Name = "Hold Back the Rain",
                            Track = 5
                        },
                        new
                        {
                            Id = 33L,
                            AlbumId = 3L,
                            Created = new DateTimeOffset(new DateTime(2022, 9, 28, 16, 24, 43, 499, DateTimeKind.Unspecified).AddTicks(3391), new TimeSpan(0, -4, 0, 0, 0)),
                            Name = "New Religion",
                            Track = 6
                        },
                        new
                        {
                            Id = 34L,
                            AlbumId = 3L,
                            Created = new DateTimeOffset(new DateTime(2022, 9, 28, 16, 24, 43, 499, DateTimeKind.Unspecified).AddTicks(3404), new TimeSpan(0, -4, 0, 0, 0)),
                            Name = "Last Chance on the Stairway",
                            Track = 7
                        },
                        new
                        {
                            Id = 35L,
                            AlbumId = 3L,
                            Created = new DateTimeOffset(new DateTime(2022, 9, 28, 16, 24, 43, 499, DateTimeKind.Unspecified).AddTicks(3416), new TimeSpan(0, -4, 0, 0, 0)),
                            Name = "Save a Prayer",
                            Track = 8
                        },
                        new
                        {
                            Id = 36L,
                            AlbumId = 3L,
                            Created = new DateTimeOffset(new DateTime(2022, 9, 28, 16, 24, 43, 499, DateTimeKind.Unspecified).AddTicks(3427), new TimeSpan(0, -4, 0, 0, 0)),
                            Name = "The Chauffeur",
                            Track = 9
                        },
                        new
                        {
                            Id = 37L,
                            AlbumId = 4L,
                            Created = new DateTimeOffset(new DateTime(2022, 9, 28, 16, 24, 43, 499, DateTimeKind.Unspecified).AddTicks(3475), new TimeSpan(0, -4, 0, 0, 0)),
                            Name = "1984",
                            Track = 1
                        },
                        new
                        {
                            Id = 38L,
                            AlbumId = 4L,
                            Created = new DateTimeOffset(new DateTime(2022, 9, 28, 16, 24, 43, 499, DateTimeKind.Unspecified).AddTicks(3488), new TimeSpan(0, -4, 0, 0, 0)),
                            Name = "Jump",
                            Track = 2
                        },
                        new
                        {
                            Id = 39L,
                            AlbumId = 4L,
                            Created = new DateTimeOffset(new DateTime(2022, 9, 28, 16, 24, 43, 499, DateTimeKind.Unspecified).AddTicks(3500), new TimeSpan(0, -4, 0, 0, 0)),
                            Name = "Panama",
                            Track = 3
                        },
                        new
                        {
                            Id = 40L,
                            AlbumId = 4L,
                            Created = new DateTimeOffset(new DateTime(2022, 9, 28, 16, 24, 43, 499, DateTimeKind.Unspecified).AddTicks(3511), new TimeSpan(0, -4, 0, 0, 0)),
                            Name = "Top Jimmy",
                            Track = 4
                        },
                        new
                        {
                            Id = 41L,
                            AlbumId = 4L,
                            Created = new DateTimeOffset(new DateTime(2022, 9, 28, 16, 24, 43, 499, DateTimeKind.Unspecified).AddTicks(3523), new TimeSpan(0, -4, 0, 0, 0)),
                            Name = "Drop Dead Legs",
                            Track = 5
                        },
                        new
                        {
                            Id = 42L,
                            AlbumId = 4L,
                            Created = new DateTimeOffset(new DateTime(2022, 9, 28, 16, 24, 43, 499, DateTimeKind.Unspecified).AddTicks(3535), new TimeSpan(0, -4, 0, 0, 0)),
                            Name = "Hot for Teacher",
                            Track = 6
                        },
                        new
                        {
                            Id = 43L,
                            AlbumId = 4L,
                            Created = new DateTimeOffset(new DateTime(2022, 9, 28, 16, 24, 43, 499, DateTimeKind.Unspecified).AddTicks(3546), new TimeSpan(0, -4, 0, 0, 0)),
                            Name = "I'll Wait",
                            Track = 7
                        },
                        new
                        {
                            Id = 44L,
                            AlbumId = 4L,
                            Created = new DateTimeOffset(new DateTime(2022, 9, 28, 16, 24, 43, 499, DateTimeKind.Unspecified).AddTicks(3557), new TimeSpan(0, -4, 0, 0, 0)),
                            Name = "Girl Gone Bad",
                            Track = 8
                        },
                        new
                        {
                            Id = 45L,
                            AlbumId = 4L,
                            Created = new DateTimeOffset(new DateTime(2022, 9, 28, 16, 24, 43, 499, DateTimeKind.Unspecified).AddTicks(3569), new TimeSpan(0, -4, 0, 0, 0)),
                            Name = "House of Pain",
                            Track = 9
                        });
                });

            modelBuilder.Entity("DaveNatalie.CarMediaDevTest.Models.Album", b =>
                {
                    b.HasOne("DaveNatalie.CarMediaDevTest.Models.Artist", "Artist")
                        .WithMany("Albums")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("DaveNatalie.CarMediaDevTest.Models.Song", b =>
                {
                    b.HasOne("DaveNatalie.CarMediaDevTest.Models.Album", "Album")
                        .WithMany("Songs")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");
                });

            modelBuilder.Entity("DaveNatalie.CarMediaDevTest.Models.Album", b =>
                {
                    b.Navigation("Songs");
                });

            modelBuilder.Entity("DaveNatalie.CarMediaDevTest.Models.Artist", b =>
                {
                    b.Navigation("Albums");
                });
#pragma warning restore 612, 618
        }
    }
}
